### PR TITLE
chore: change default wallet path to root directory

### PR DESCRIPTION
**Pull request by holazz**

### CODE REVIEW

**Comment by atomicals** [comment]
Please rebase and submit again, thank you

**Comment by holazz** [comment]
> Please rebase and submit again, thank you

Done!

**Comment by AlexV525** [comment]
Please avoid changing `.env` in further requests. This will cause users to drop their configurations unexpectedly.

**Comment by holazz** [comment]
> Please avoid changing `.env` in further requests. This will cause users to drop their configurations unexpectedly.

Ok, I will close it.

**Pull request closed without merging**
