### PR TITLE
not using process.stdout

### PR DESCRIPTION
**Pull request by BenedictKing**
using process.stdout always got error when run with pm2

### CODE REVIEW

**Comment by wusimpl** [comment]
do u mean #136 "process.stdout.clearLine is not function" error？okay, so which method should we take? switch to console.log or use process.stdout.clearLine?.(0)？

**Comment by BenedictKing** [comment]
> do u mean #136 "process.stdout.clearLine is not function" error？okay, so which method should we take? switch to console.log or use process.stdout.clearLine?.(0)？

I prefer using console.log as I did

**Comment by atomicals** [comment]
Will this log many times to the console and flood the screen?

**Comment by BenedictKing** [comment]
I always run with --disablechalk so I guess yes.

**Pull request closed without merging**
