### PR TITLE
[PoW Lab] Enhance hash rate 5x by reducing the use of  `await sleep(0)`.

### PR DESCRIPTION
**Pull request by pow-lab**
# What

We ([PoW Lab](https://twitter.com/pow_lab)) are dedicated to promoting Proof of Work (PoW) consensus and firmly believe that PoW consensus is the fairest game in the blockchain space. We appreciate the Atomicals project but have identified several issues in this project (atomicals-js) that affect mining hash rates. Therefore, we have decided to optimize the open-source code through our efforts to ensure that everyone can achieve high hash rates. This is the first in our series of PRs.

# How

Firstly, we added a [commit](https://github.com/atomicals/atomicals-js/commit/4996dca39334874c45670fa8f545a39bd0c5d2b5) that outputs hash rates every 10,000 hashes. The purpose is to quantify hash rates more clearly for subsequent optimizations.

Then, in this [commit](https://github.com/atomicals/atomicals-js/commit/34a249117e891351839ac091d9aecc238beb3061), we modified the position of `await sleep(0)`, significantly reducing its number of calls and thereby increasing the hash rate by approximately 5 times.

# Why

The essence of `await sleep(0)` is calling `setTimeout(fn, 0)`. As [this document](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#nested_timeouts) shows, even with 0 milliseconds as a parameter, setTimeout may still be executed with a delay of 4 milliseconds. This prevents PoW mining code from running at 100% capacity, significantly reducing mining hash rates. According to our practical tests, using a single thread on an M1 Max MacBook Pro (`CONCURRENCY=1`) resulted in over a 5x improvement:

Before:

Before

After:

After

---

# 是什么

我们（[PoW Lab](https://twitter.com/pow_lab)）致力于推动工作证明（PoW）共识，并坚信PoW共识是区块链领域中最公平的游戏。我们赞赏Atomicals项目，但在该项目（atomicals-js）中发现了一些影响挖矿算力的问题。因此，我们决定通过我们的努力优化开源代码，以确保每个人都能实现高算力。这是我们系列PR中的第一个。

# 怎么做

首先，我们添加了一个[提交](https://github.com/atomicals/atomicals-js/commit/4996dca39334874c45670fa8f545a39bd0c5d2b5)，每10,000个哈希输出一次算力。目的是为了更清晰地量化后续的优化算力。

然后，在这个[提交](https://github.com/atomicals/atomicals-js/commit/34a249117e891351839ac091d9aecc238beb3061)中，我们修改了`await sleep(0)`的位置，显著减少了它的调用次数，从而将算力提高了约5倍。

# 为什么

`await sleep(0)`的本质是调用`setTimeout(fn, 0)`。正如[这份文档](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#nested_timeouts)所示，即使参数为0毫秒，setTimeout仍可能延迟4毫秒执行。这阻止了PoW挖矿代码以100%的容量运行，从而显著降低了挖矿算力。根据我们的实际测试，在M1 Max MacBook Pro上使用单线程（`CONCURRENCY=1`）实现了5倍以上的改善：

之前：

之前

之后：

之后

### CODE REVIEW

**Comment by AlexV525** [comment]
Which means @NeutronProtocol 's improvement with (`10x` * `15x`) is non-sense. LMAO

- https://github.com/atomicals/atomicals-js/pull/152
- https://github.com/atomicals/atomicals-js/pull/156

**Comment by pow-lab** [comment]
@AlexV525 I'm not sure. However, some of their work does seem meaningful, such as utilizing sequences to reduce redundant production of AtomicsPayload. This, to some extent, can improve hash rates.

Nevertheless, we believe that mining performance should ultimately be evaluated based on hash rates. Producing reproducible results with the same hardware configuration is the most indicative. We'll stick to this principle in the upcoming optimization processes. Stay tuned.

@AlexV525 我不太确定。但是他们的一些工作似乎是有意义的，比如利用 sequences 来减少冗余的 AtomicsPayload 生产。在某种程度上，这可以提高哈希率。

然而，我们认为挖矿性能最终应该基于哈希率进行评估。使用相同的硬件配置产生可重复的结果是最有说服力的。在接下来的优化过程中，我们将坚持这个原则。敬请关注。

**Comment by AlexV525** [comment]
> @AlexV525 I'm not sure. However, some of their work does seem meaningful, such as utilizing sequences to reduce redundant production of AtomicsPayload. This, to some extent, can improve hash rates.

Yes I was only talking about the *times* they have mentioned. Great job anyway.

**Comment by pow-lab** [comment]
@atomicals Could you please take a look?

**Comment by atomicals** [comment]
Awesome change! Thank you!

**Comment by NeutronProtocol** [comment]
> Which means @NeutronProtocol 's improvement with (`10x` * `15x`) is non-sense. LMAO
> 
> * [[Neutron Protocol]10x speed boost POW: Use sequence to calculate Bitwork #152](https://github.com/atomicals/atomicals-js/pull/152)
> * [[Hotfix] Fix Sequence issues and accelerate 15x more #156](https://github.com/atomicals/atomicals-js/pull/156)

Regarding recent discussions about our improvements, we'd like to provide some clarity. The numbers we've shared are based on actual data, tracking the time it takes to mint tokens like Quark. Our enhancements have indeed significantly increased computing speeds, turning what used to be hours into mere minutes for minting a 6-d token.

We also acknowledge the room for improvement, particularly with the sleep(0) mechanism. A special shoutout to @pow-lab for their valuable tweak, enhancing the process further. This collaborative spirit is at the heart of Neutron Labs. Our mission to promote fair POW and make ARC20 Bitwork POW accessible to all in the ARC20 world is resonating, and we're thrilled to see that there're actually more people that are inspired by our day-1 mission. 

Thank you all for making Atomicals great!

**Pull request merged**
