### PR TITLE
Fix the problem of different Reveal gas fees caused by using bitwork

### PR DESCRIPTION
**Pull request by lyen1688**
Fixed the problem of fee inconsistency in the second broadcast.

### CODE REVIEW

**Comment by atlaslabsapp** [comment]
Have you tried to mint something without `bitworkr` to check if it is right?

**Comment by lyen1688** [comment]
[[patch-1](https://github.com/lyen1688/atomicals-js/tree/patch-1)](https://github.com/atomicals/atomicals-js/pull/237/commits/7f3ff75c7447774fe05db5d75fe39e81d81c1e92)

We have fixed the issue where tokens or NFTs with bitworkr set were adding additional outputs in the transaction for storing time and random number information, resulting in increased fees. This caused the fee in the second broadcast to be inconsistent with the first.

In the new version, I have added a judgment for bitworkr to avoid those tokens or NFTs that do not have bitworkr set, which also increases the fee.

**Comment by lyen1688** [comment]
@atomicals Please review and merge as soon as possible!

**Comment by atomicals** [comment]
Can you please rebase and check if this is still needed with the most recent pr merge?

**Comment by lyen1688** [comment]
#243 The problem solved is the same as mine. But I was the first to identify the problem and come up with a solution. Why did someone else re-issue a PR later, but you chose to merge his PR first?

**Comment by AndyJiangPro** [comment]
it looks good to me

**Review by NeutronProtocol — APPROVED** [review]

**Comment by atomicals** [comment]
> #243 The problem solved is the same as mine. But I was the first to identify the problem and come up with a solution. But he re-issued the PR later, so why did you choose to ignore me and adopt his PR first? This is very unfair and disrespectful to the contributors! @atomicals
> 
> https://twitter.com/1999_eth/status/1747141263961239878

My apologies, I just went through the list and didn't realize there were double PRs that solved the same issue.  I'll merge this one you have created here now since I like the naming better and you add extra calculation for op_return

**Comment by atomicals** [comment]
Merging these changes. Thank you very much!

**Comment by atomicals** [comment]
> it looks good to me

@AndyJiangPro How did you make your change in PR  https://github.com/atomicals/atomicals-js/pull/243 ? 

Please check if an existing PR already addresses a problem you have fixed. This goes for me too because I made the mistake of checking newer PR instead of previous existing ones.  

I will be more careful to check existing PR first in the future to ensure the earlier work is recognized. I kindly request that you also chck for existing PR and contribute to the existing ones so we minimize duplicate work and also recognize the order of the contributions.  Thank you for your understanding.

Thank you @lyen1688 for identifying and producing the first fix for this and thank you also for @AndyJiangPro to have the keen interest to assist in the solution.

**Pull request merged**
